# Generated by Django 5.1.7 on 2025-03-13 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprof', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecontent',
            name='course',
        ),
    ]
