# Generated by Django 5.1.4 on 2025-04-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprof', '0003_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='difficulty_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], default='beginner', max_length=20),
        ),
    ]
