# Generated by Django 5.1.4 on 2025-04-06 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprof', '0004_userprofile_difficulty_level'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursecontent',
            unique_together=set(),
        ),
    ]
