# Generated by Django 5.1.7 on 2025-03-16 06:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='module',
        ),
        migrations.RemoveField(
            model_name='questionoption',
            name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='is_ai_generated',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='time_limit_minutes',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='assessmentattempt',
            name='passing_score',
        ),
        migrations.RemoveField(
            model_name='assessmentattempt',
            name='time_spent_minutes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='question',
            name='difficulty_level',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_ai_generated',
        ),
        migrations.RemoveField(
            model_name='question',
            name='order_index',
        ),
        migrations.RemoveField(
            model_name='question',
            name='points',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='feedback',
        ),
        migrations.AddField(
            model_name='assessment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessment',
            name='time_limit',
            field=models.PositiveIntegerField(default=30, help_text='Time in minutes'),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='passing_score',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='assessmentattempt',
            name='completed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assessmentattempt',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assessmentattempt',
            name='started_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessment.assessment'),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assessment.assessmentattempt'),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='points_awarded',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='response_text',
            field=models.TextField(blank=True, default='response is not present'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='assessment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='assessmentattempt',
            table=None,
        ),
        migrations.AlterModelTable(
            name='question',
            table=None,
        ),
        migrations.AlterModelTable(
            name='userresponse',
            table=None,
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='assessment.question')),
            ],
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='selected_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessment.option'),
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.DeleteModel(
            name='QuestionOption',
        ),
    ]
