# Generated by Django 5.1.4 on 2025-04-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='course_content_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='course_content_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
