# Generated by Django 5.1.4 on 2025-04-06 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_concept_learningpath_learningpathnode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='learningpath',
            name='course_content_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningpath',
            name='course_content_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='learningpath',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='learningpath',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_paths', to=settings.AUTH_USER_MODEL),
        ),
    ]
